"""add Department

Revision ID: 006dd7ca2ef3
Revises: cc5acabc77ac
Create Date: 2024-03-08 16:56:50.902134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006dd7ca2ef3'
down_revision = 'cc5acabc77ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
