"""rename department

Revision ID: 50978936e436
Revises: 006dd7ca2ef3
Create Date: 2024-03-08 16:59:30.615966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50978936e436'
down_revision = '006dd7ca2ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
